// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// clark_wright.cpp
list clark_wright(const std::vector<int> & demand, const std::vector<double> & distances);
extern "C" SEXP _heumilkr_clark_wright(SEXP demand, SEXP distances) {
  BEGIN_CPP11
    return cpp11::as_sexp(clark_wright(cpp11::as_cpp<cpp11::decay_t<const std::vector<int> &>>(demand), cpp11::as_cpp<cpp11::decay_t<const std::vector<double> &>>(distances)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_heumilkr_clark_wright", (DL_FUNC) &_heumilkr_clark_wright, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_heumilkr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
