debug: clarke_wright.cpp fleet.cpp cpp11.cpp symmat.cpp run.cpp router.cpp tsp_greedy.cpp
	g++ -std=gnu++17 -I. \
		-fdiagnostics-color=never \
		-fstack-protector-strong -fstack-clash-protection -Wformat -fcf-protection \
		-Wdate-time -Wall -pedantic -Wformat-security -g -O0 \
		-fsanitize=address,undefined \
		clarke_wright.cpp fleet.cpp symmat.cpp run.cpp router.cpp tsp_greedy.cpp \
		-o debug
